version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - BACKEND_HOST=${BACKEND_HOST:-localhost}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST: db
      - DB_USER: ${MYSQL_USER}
      - DB_PASSWORD: ${MYSQL_PASSWORD}
      - DB_NAME: ${MYSQL_DATABASE}
      - JWT_SECRET: ${JWT_SECRET} 
    depends_on:
      - db

  db:
  image: mysql:8.0
  environment:
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  volumes:
    - mysql_data:/var/lib/mysqls
    - ./back/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  ports:
    - "3333:3333"

volumes:
  mysql_data: